/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        surface: {
          DEFAULT: '#ffffff',
          dim: '#fafafa',
          bright: '#ffffff',
          'container-lowest': '#fafafa',
          'container-low': '#f4f4f5',
          container: '#f4f4f5',
          'container-high': '#ececee',
          'container-highest': '#e4e4e7',
          variant: '#e4e4e7',
          tint: '#0d9488',
        },
        primary: {
          DEFAULT: '#0d9488',
          dim: '#0f766e',
          fixed: '#14b8a6',
          'fixed-dim': '#0d9488',
          container: '#2dd4bf',
        },
        'on-primary': {
          DEFAULT: '#ffffff',
          container: '#042f2e',
          fixed: '#ffffff',
          'fixed-variant': '#f0fdfa',
        },
        secondary: {
          DEFAULT: '#059669',
          dim: '#047857',
          fixed: '#10b981',
          'fixed-dim': '#059669',
          container: '#d1fae5',
        },
        'on-secondary': { DEFAULT: '#ffffff', container: '#064e3b', fixed: '#ffffff', 'fixed-variant': '#065f46' },
        tertiary: {
          DEFAULT: '#7c3aed',
          dim: '#6d28d9',
          fixed: '#8b5cf6',
          'fixed-dim': '#7c3aed',
          container: '#ede9fe',
        },
        'on-tertiary': { DEFAULT: '#ffffff', container: '#4c1d95', fixed: '#ffffff', 'fixed-variant': '#5b21b6' },
        error: {
          DEFAULT: '#dc2626',
          dim: '#b91c1c',
          container: '#fee2e2',
        },
        'on-error': { DEFAULT: '#ffffff', container: '#7f1d1d' },
        'on-surface': { DEFAULT: '#18181b', variant: '#52525b' },
        'on-background': '#18181b',
        outline: { DEFAULT: '#d4d4d8', variant: '#a1a1aa' },
        'inverse-surface': '#18181b',
        'inverse-on-surface': '#fafafa',
        'inverse-primary': '#5eead4',
      },
      fontFamily: {
        headline: ['Manrope', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        label: ['Inter', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        sm: '0.125rem',
        md: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
      },
      boxShadow: {
        soft: '0 1px 3px 0 rgb(0 0 0 / 0.06), 0 1px 2px -1px rgb(0 0 0 / 0.06)',
        card: '0 4px 6px -1px rgb(0 0 0 / 0.05), 0 2px 4px -2px rgb(0 0 0 / 0.05)',
        lift: '0 10px 40px -10px rgb(0 0 0 / 0.12)',
      },
    },
  },
  plugins: [],
}
